// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.kaneki.xim.protoc;

public final class XProtocol {
  private XProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.kaneki.xim.protoc.XProtocol.requset);
    registry.add(com.kaneki.xim.protoc.XProtocol.respone);
    registry.add(com.kaneki.xim.protoc.XProtocol.push);
    registry.add(com.kaneki.xim.protoc.XProtocol.message);
  }
  /**
   * Protobuf enum {@code Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BASE_TYPE_REQUEST = 0;</code>
     */
    BASE_TYPE_REQUEST(0, 0),
    /**
     * <code>BASE_TYPE_RESPONSE = 1;</code>
     */
    BASE_TYPE_RESPONSE(1, 1),
    /**
     * <code>BASE_TYPE_PUSH = 2;</code>
     */
    BASE_TYPE_PUSH(2, 2),
    /**
     * <code>BASE_TYPE_MESSAGE = 3;</code>
     */
    BASE_TYPE_MESSAGE(3, 3),
    ;

    /**
     * <code>BASE_TYPE_REQUEST = 0;</code>
     */
    public static final int BASE_TYPE_REQUEST_VALUE = 0;
    /**
     * <code>BASE_TYPE_RESPONSE = 1;</code>
     */
    public static final int BASE_TYPE_RESPONSE_VALUE = 1;
    /**
     * <code>BASE_TYPE_PUSH = 2;</code>
     */
    public static final int BASE_TYPE_PUSH_VALUE = 2;
    /**
     * <code>BASE_TYPE_MESSAGE = 3;</code>
     */
    public static final int BASE_TYPE_MESSAGE_VALUE = 3;


    public final int getNumber() { return value; }

    public static Type valueOf(int value) {
      switch (value) {
        case 0: return BASE_TYPE_REQUEST;
        case 1: return BASE_TYPE_RESPONSE;
        case 2: return BASE_TYPE_PUSH;
        case 3: return BASE_TYPE_MESSAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kaneki.xim.protoc.XProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Type)
  }

  public interface ProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protocol)
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Protocol> {

    /**
     * <code>required .Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .Type type = 1;</code>
     */
    com.kaneki.xim.protoc.XProtocol.Type getType();

    /**
     * <code>required int64 toId = 2;</code>
     */
    boolean hasToId();
    /**
     * <code>required int64 toId = 2;</code>
     */
    long getToId();

    /**
     * <code>required int64 fromId = 3;</code>
     */
    boolean hasFromId();
    /**
     * <code>required int64 fromId = 3;</code>
     */
    long getFromId();

    /**
     * <code>required string packetId = 4;</code>
     */
    boolean hasPacketId();
    /**
     * <code>required string packetId = 4;</code>
     */
    java.lang.String getPacketId();
    /**
     * <code>required string packetId = 4;</code>
     */
    com.google.protobuf.ByteString
        getPacketIdBytes();

    /**
     * <code>required int64 packetSize = 5;</code>
     */
    boolean hasPacketSize();
    /**
     * <code>required int64 packetSize = 5;</code>
     */
    long getPacketSize();

    /**
     * <code>required int64 created = 6;</code>
     */
    boolean hasCreated();
    /**
     * <code>required int64 created = 6;</code>
     */
    long getCreated();
  }
  /**
   * Protobuf type {@code Protocol}
   */
  public static final class Protocol extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Protocol> implements
      // @@protoc_insertion_point(message_implements:Protocol)
      ProtocolOrBuilder {
    // Use Protocol.newBuilder() to construct.
    private Protocol(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.kaneki.xim.protoc.XProtocol.Protocol, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Protocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Protocol defaultInstance;
    public static Protocol getDefaultInstance() {
      return defaultInstance;
    }

    public Protocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Protocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.kaneki.xim.protoc.XProtocol.Type value = com.kaneki.xim.protoc.XProtocol.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              toId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fromId_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              packetId_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              packetSize_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              created_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kaneki.xim.protoc.XProtocol.internal_static_Protocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kaneki.xim.protoc.XProtocol.internal_static_Protocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kaneki.xim.protoc.XProtocol.Protocol.class, com.kaneki.xim.protoc.XProtocol.Protocol.Builder.class);
    }

    public static com.google.protobuf.Parser<Protocol> PARSER =
        new com.google.protobuf.AbstractParser<Protocol>() {
      public Protocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Protocol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Protocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.kaneki.xim.protoc.XProtocol.Type type_;
    /**
     * <code>required .Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Type type = 1;</code>
     */
    public com.kaneki.xim.protoc.XProtocol.Type getType() {
      return type_;
    }

    public static final int TOID_FIELD_NUMBER = 2;
    private long toId_;
    /**
     * <code>required int64 toId = 2;</code>
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 toId = 2;</code>
     */
    public long getToId() {
      return toId_;
    }

    public static final int FROMID_FIELD_NUMBER = 3;
    private long fromId_;
    /**
     * <code>required int64 fromId = 3;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 fromId = 3;</code>
     */
    public long getFromId() {
      return fromId_;
    }

    public static final int PACKETID_FIELD_NUMBER = 4;
    private java.lang.Object packetId_;
    /**
     * <code>required string packetId = 4;</code>
     */
    public boolean hasPacketId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string packetId = 4;</code>
     */
    public java.lang.String getPacketId() {
      java.lang.Object ref = packetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packetId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string packetId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPacketIdBytes() {
      java.lang.Object ref = packetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKETSIZE_FIELD_NUMBER = 5;
    private long packetSize_;
    /**
     * <code>required int64 packetSize = 5;</code>
     */
    public boolean hasPacketSize() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 packetSize = 5;</code>
     */
    public long getPacketSize() {
      return packetSize_;
    }

    public static final int CREATED_FIELD_NUMBER = 6;
    private long created_;
    /**
     * <code>required int64 created = 6;</code>
     */
    public boolean hasCreated() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 created = 6;</code>
     */
    public long getCreated() {
      return created_;
    }

    private void initFields() {
      type_ = com.kaneki.xim.protoc.XProtocol.Type.BASE_TYPE_REQUEST;
      toId_ = 0L;
      fromId_ = 0L;
      packetId_ = "";
      packetSize_ = 0L;
      created_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPacketId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPacketSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.kaneki.xim.protoc.XProtocol.Protocol>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, toId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, fromId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPacketIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, packetSize_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, created_);
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, toId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fromId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPacketIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, packetSize_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, created_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kaneki.xim.protoc.XProtocol.Protocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kaneki.xim.protoc.XProtocol.Protocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kaneki.xim.protoc.XProtocol.Protocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kaneki.xim.protoc.XProtocol.Protocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kaneki.xim.protoc.XProtocol.Protocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kaneki.xim.protoc.XProtocol.Protocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kaneki.xim.protoc.XProtocol.Protocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kaneki.xim.protoc.XProtocol.Protocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kaneki.xim.protoc.XProtocol.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kaneki.xim.protoc.XProtocol.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kaneki.xim.protoc.XProtocol.Protocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.kaneki.xim.protoc.XProtocol.Protocol, Builder> implements
        // @@protoc_insertion_point(builder_implements:Protocol)
        com.kaneki.xim.protoc.XProtocol.ProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kaneki.xim.protoc.XProtocol.internal_static_Protocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kaneki.xim.protoc.XProtocol.internal_static_Protocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kaneki.xim.protoc.XProtocol.Protocol.class, com.kaneki.xim.protoc.XProtocol.Protocol.Builder.class);
      }

      // Construct using com.kaneki.xim.protoc.XProtocol.Protocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.kaneki.xim.protoc.XProtocol.Type.BASE_TYPE_REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        toId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        fromId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        packetId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        packetSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        created_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kaneki.xim.protoc.XProtocol.internal_static_Protocol_descriptor;
      }

      public com.kaneki.xim.protoc.XProtocol.Protocol getDefaultInstanceForType() {
        return com.kaneki.xim.protoc.XProtocol.Protocol.getDefaultInstance();
      }

      public com.kaneki.xim.protoc.XProtocol.Protocol build() {
        com.kaneki.xim.protoc.XProtocol.Protocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kaneki.xim.protoc.XProtocol.Protocol buildPartial() {
        com.kaneki.xim.protoc.XProtocol.Protocol result = new com.kaneki.xim.protoc.XProtocol.Protocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toId_ = toId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.packetId_ = packetId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.packetSize_ = packetSize_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.created_ = created_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kaneki.xim.protoc.XProtocol.Protocol) {
          return mergeFrom((com.kaneki.xim.protoc.XProtocol.Protocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kaneki.xim.protoc.XProtocol.Protocol other) {
        if (other == com.kaneki.xim.protoc.XProtocol.Protocol.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasToId()) {
          setToId(other.getToId());
        }
        if (other.hasFromId()) {
          setFromId(other.getFromId());
        }
        if (other.hasPacketId()) {
          bitField0_ |= 0x00000008;
          packetId_ = other.packetId_;
          onChanged();
        }
        if (other.hasPacketSize()) {
          setPacketSize(other.getPacketSize());
        }
        if (other.hasCreated()) {
          setCreated(other.getCreated());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasToId()) {
          
          return false;
        }
        if (!hasFromId()) {
          
          return false;
        }
        if (!hasPacketId()) {
          
          return false;
        }
        if (!hasPacketSize()) {
          
          return false;
        }
        if (!hasCreated()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kaneki.xim.protoc.XProtocol.Protocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kaneki.xim.protoc.XProtocol.Protocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.kaneki.xim.protoc.XProtocol.Type type_ = com.kaneki.xim.protoc.XProtocol.Type.BASE_TYPE_REQUEST;
      /**
       * <code>required .Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Type type = 1;</code>
       */
      public com.kaneki.xim.protoc.XProtocol.Type getType() {
        return type_;
      }
      /**
       * <code>required .Type type = 1;</code>
       */
      public Builder setType(com.kaneki.xim.protoc.XProtocol.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.kaneki.xim.protoc.XProtocol.Type.BASE_TYPE_REQUEST;
        onChanged();
        return this;
      }

      private long toId_ ;
      /**
       * <code>required int64 toId = 2;</code>
       */
      public boolean hasToId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 toId = 2;</code>
       */
      public long getToId() {
        return toId_;
      }
      /**
       * <code>required int64 toId = 2;</code>
       */
      public Builder setToId(long value) {
        bitField0_ |= 0x00000002;
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 toId = 2;</code>
       */
      public Builder clearToId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toId_ = 0L;
        onChanged();
        return this;
      }

      private long fromId_ ;
      /**
       * <code>required int64 fromId = 3;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 fromId = 3;</code>
       */
      public long getFromId() {
        return fromId_;
      }
      /**
       * <code>required int64 fromId = 3;</code>
       */
      public Builder setFromId(long value) {
        bitField0_ |= 0x00000004;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fromId = 3;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object packetId_ = "";
      /**
       * <code>required string packetId = 4;</code>
       */
      public boolean hasPacketId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string packetId = 4;</code>
       */
      public java.lang.String getPacketId() {
        java.lang.Object ref = packetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packetId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string packetId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPacketIdBytes() {
        java.lang.Object ref = packetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string packetId = 4;</code>
       */
      public Builder setPacketId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string packetId = 4;</code>
       */
      public Builder clearPacketId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        packetId_ = getDefaultInstance().getPacketId();
        onChanged();
        return this;
      }
      /**
       * <code>required string packetId = 4;</code>
       */
      public Builder setPacketIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        packetId_ = value;
        onChanged();
        return this;
      }

      private long packetSize_ ;
      /**
       * <code>required int64 packetSize = 5;</code>
       */
      public boolean hasPacketSize() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 packetSize = 5;</code>
       */
      public long getPacketSize() {
        return packetSize_;
      }
      /**
       * <code>required int64 packetSize = 5;</code>
       */
      public Builder setPacketSize(long value) {
        bitField0_ |= 0x00000010;
        packetSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 packetSize = 5;</code>
       */
      public Builder clearPacketSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        packetSize_ = 0L;
        onChanged();
        return this;
      }

      private long created_ ;
      /**
       * <code>required int64 created = 6;</code>
       */
      public boolean hasCreated() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 created = 6;</code>
       */
      public long getCreated() {
        return created_;
      }
      /**
       * <code>required int64 created = 6;</code>
       */
      public Builder setCreated(long value) {
        bitField0_ |= 0x00000020;
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 created = 6;</code>
       */
      public Builder clearCreated() {
        bitField0_ = (bitField0_ & ~0x00000020);
        created_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Protocol)
    }

    static {
      defaultInstance = new Protocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Protocol)
  }

  public static final int REQUSET_FIELD_NUMBER = 100;
  /**
   * <code>extend .Protocol { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.kaneki.xim.protoc.XProtocol.Protocol,
      com.kaneki.xim.protoc.request.XRequest.Request> requset = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.kaneki.xim.protoc.request.XRequest.Request.class,
        com.kaneki.xim.protoc.request.XRequest.Request.getDefaultInstance());
  public static final int RESPONE_FIELD_NUMBER = 101;
  /**
   * <code>extend .Protocol { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.kaneki.xim.protoc.XProtocol.Protocol,
      com.kaneki.xim.protoc.response.XResponse.Response> respone = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.kaneki.xim.protoc.response.XResponse.Response.class,
        com.kaneki.xim.protoc.response.XResponse.Response.getDefaultInstance());
  public static final int PUSH_FIELD_NUMBER = 102;
  /**
   * <code>extend .Protocol { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.kaneki.xim.protoc.XProtocol.Protocol,
      com.kaneki.xim.protoc.push.XPush.Push> push = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.kaneki.xim.protoc.push.XPush.Push.class,
        com.kaneki.xim.protoc.push.XPush.Push.getDefaultInstance());
  public static final int MESSAGE_FIELD_NUMBER = 103;
  /**
   * <code>extend .Protocol { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.kaneki.xim.protoc.XProtocol.Protocol,
      com.kaneki.xim.protoc.message.XMessage.Message> message = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.kaneki.xim.protoc.message.XMessage.Message.class,
        com.kaneki.xim.protoc.message.XMessage.Message.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\032\025request/request.proto\032" +
      "\027response/response.proto\032\017push/push.prot" +
      "o\032\025message/message.proto\"~\n\010Protocol\022\023\n\004" +
      "type\030\001 \002(\0162\005.Type\022\014\n\004toId\030\002 \002(\003\022\016\n\006fromI" +
      "d\030\003 \002(\003\022\020\n\010packetId\030\004 \002(\t\022\022\n\npacketSize\030" +
      "\005 \002(\003\022\017\n\007created\030\006 \002(\003*\010\010d\020\200\200\200\200\002*`\n\004Type" +
      "\022\025\n\021BASE_TYPE_REQUEST\020\000\022\026\n\022BASE_TYPE_RES" +
      "PONSE\020\001\022\022\n\016BASE_TYPE_PUSH\020\002\022\025\n\021BASE_TYPE" +
      "_MESSAGE\020\003:$\n\007requset\022\t.Protocol\030d \001(\0132\010" +
      ".Request:%\n\007respone\022\t.Protocol\030e \001(\0132\t.R",
      "esponse:\036\n\004push\022\t.Protocol\030f \001(\0132\005.Push:" +
      "$\n\007message\022\t.Protocol\030g \001(\0132\010.MessageB\"\n" +
      "\025com.kaneki.xim.protocB\tXProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kaneki.xim.protoc.request.XRequest.getDescriptor(),
          com.kaneki.xim.protoc.response.XResponse.getDescriptor(),
          com.kaneki.xim.protoc.push.XPush.getDescriptor(),
          com.kaneki.xim.protoc.message.XMessage.getDescriptor(),
        }, assigner);
    internal_static_Protocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Protocol_descriptor,
        new java.lang.String[] { "Type", "ToId", "FromId", "PacketId", "PacketSize", "Created", });
    requset.internalInit(descriptor.getExtensions().get(0));
    respone.internalInit(descriptor.getExtensions().get(1));
    push.internalInit(descriptor.getExtensions().get(2));
    message.internalInit(descriptor.getExtensions().get(3));
    com.kaneki.xim.protoc.request.XRequest.getDescriptor();
    com.kaneki.xim.protoc.response.XResponse.getDescriptor();
    com.kaneki.xim.protoc.push.XPush.getDescriptor();
    com.kaneki.xim.protoc.message.XMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
